# -*- coding: utf-8 -*-
"""SuperStores_Forecast_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sil211w7QMTXR6x8m24-v-5BKhOrFyEM
"""

!pip install pmdarima

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (15, 6)
plt.rcParams['font.size'] = 11

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller, acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.holtwinters import ExponentialSmoothing

from pmdarima import auto_arima

from sklearn.metrics import mean_squared_error, mean_absolute_error

df = pd.read_csv("SuperStoreOrders.csv")
df.head()

df.info()

df.isnull().sum()

df.describe()

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df.dtypes

df = df.sort_values('order_date')
print(df['order_date'].min())
print(df['order_date'].max())

df['order_date'].dt.to_period('M').value_counts().sort_index()

df.set_index('order_date', inplace=True)

df['sales'] = df['sales'].astype(str)  
df['sales'] = df['sales'].str.replace(',', '')  
df['sales'] = df['sales'].astype(float)

monthly_sales = df['sales'].resample('M').sum()

monthly_sales.head()
monthly_sales.dtype

decomp = seasonal_decompose(monthly_sales, model='additive', period=12)

plt.figure(figsize=(10,5))
decomp.observed.plot(title='Numbers of  order (2011-2014)\n',
                     xlabel='year', ylabel='Order')
plt.tight_layout()
plt.show()

ts_data = df['sales'].resample('M').sum()
print(ts_data.dtype)
len(ts_data)

from statsmodels.tsa.seasonal import seasonal_decompose

decomposition = seasonal_decompose(ts_data, model='multiplicative', period=12)

fig, axes = plt.subplots(4, 1, figsize=(15, 10))

decomposition.observed.plot(ax=axes[0])
axes[0].set_title('Observed')

decomposition.trend.plot(ax=axes[1])
axes[1].set_title('Trend')

decomposition.seasonal.plot(ax=axes[2])
axes[2].set_title('Seasonal')

decomposition.resid.plot(ax=axes[3])
axes[3].set_title('Residual')

plt.tight_layout()
plt.show()

from statsmodels.tsa.stattools import adfuller

def test_stationarity(timeseries, title="ข้อมูล"):
    """
    ทดสอบ stationarity ด้วย Augmented Dickey-Fuller test
    และแสดงผลลัพธ์อย่างละเอียด
    """

    # ทำ ADF test
    result = adfuller(timeseries.dropna(), autolag='AIC')

    print(f"\nADF Statistic: {result[0]:.6f}")
    print(f"p-value: {result[1]:.6f}")
    print(f"Number of Lags Used: {result[2]}")
    print(f"Number of Observations: {result[3]}")

    print("\nCritical Values:")
    for key, value in result[4].items():
        print(f"   {key}: {value:.4f}")

    # สรุปผล
    if result[1] <= 0.05:
        print(f"\nสรุป: {title} เป็น STATIONARY (ปฏิเสธ null hypothesis)")
        print("ข้อมูลมี statistical properties ที่คงที่ตลอดเวลา")
    else:
        print(f"\nสรุป: {title} ไม่เป็น STATIONARY (ยอมรับ null hypothesis)")
        print("ข้อมูลมี statistical properties ที่เปลี่ยนแปลงตามเวลา")

    return result[1] <= 0.05

is_stationary = test_stationarity(ts_data, "ข้อมูลยอดขาย")

ts_data_diff = ts_data.diff().dropna()
test_stationarity(ts_data_diff, "หลัง differencing ครั้งที่ 1")

train_size = len(ts_data) - 12
train_data = ts_data[:train_size]
test_data = ts_data[train_size:]

print(len(train_data))
print(len(test_data))

plt.figure(figsize=(15, 6))

plt.plot(train_data, label='Training Set', linewidth=2)
plt.plot(test_data, label='Test Set', linewidth=2)

plt.axvline(x=test_data.index[0], color='black', linestyle='--', alpha=0.5, label='Split Point')

plt.title('Split Training and Test Sets', fontsize=14, pad=15)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Sales', fontsize=12)

plt.legend(loc='upper left', fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(train_data, order=(1,1,1))
model_fit = model.fit()

forecast = model_fit.forecast(steps=len(test_data))

plt.figure(figsize=(10,5))
plt.plot(train_data, label='Train')
plt.plot(test_data, label='Actual')
plt.plot(forecast, label='Forecast')
plt.legend()
plt.show()

from pmdarima import auto_arima

auto_model = auto_arima(train_data,
                        seasonal=True,
                        m=12,
                        trace=True)

plt.figure(figsize=(12,6))

plt.plot(train_data, label='Train', color='blue')
plt.plot(test_data, label='Actual', color='black')
plt.plot(test_data.index, forecast_auto, label='Forecast (Auto ARIMA)', color='red')

plt.title("Sales Forecast Comparison")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.legend()
plt.grid()

plt.show()

forecast_auto = auto_model.predict(n_periods=len(test_data))

from sklearn.metrics import mean_absolute_error, mean_squared_error

# ARIMA เดิม
mae1 = mean_absolute_error(test_data, forecast)
rmse1 = np.sqrt(mean_squared_error(test_data, forecast))

# Auto ARIMA
mae2 = mean_absolute_error(test_data, forecast_auto)
rmse2 = np.sqrt(mean_squared_error(test_data, forecast_auto))

print("ARIMA MAE:", mae1)
print("Auto ARIMA MAE:", mae2)

print("ARIMA RMSE:", rmse1)
print("Auto ARIMA RMSE:", rmse2)

plt.figure(figsize=(10,5))

plt.plot(test_data, label='Actual', marker='o')
plt.plot(forecast, label='Forecast (ARIMA)', marker='o')
plt.plot(test_data.index, forecast_auto, label='Forecast (Auto ARIMA)', color='red', marker='o')

plt.title('Forecast vs Actual (Test Set)')
plt.legend()
plt.grid()
plt.show()

"""# **ทำการพยากรณ์จริงในระยะ1ปี**"""

auto_model = auto_arima(ts_data,
                        seasonal=False,
                        stepwise=True,
                        trace=True)

print(auto_model.summary())

future_forecast = auto_model.predict(n_periods=12)

future_index = pd.date_range(start=ts_data.index[-1], periods=13, freq='M')[1:]
future_forecast = pd.Series(future_forecast, index=future_index)

plt.figure(figsize=(10,5))

plt.plot(ts_data, label='Historical')
plt.plot(future_forecast, label='Future Forecast', color='red')

plt.title('Future Sales Forecast (Next 12 Months)')
plt.legend()
plt.grid()
plt.show()

print(auto_model.order)
